In [ ]:
from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup=requests.get(url)
soup

/usr/local/lib/python3.7/dist-packages/bs4/__init__.py:336: UserWarning: "https://www.worldometers.info/coronavirus/" looks like a URL. Beautiful Soup is not an HTTP client. You should probably use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  ' that document to Beautiful Soup.' % decoded_markup

In [ ]:
lxml_code=BeautifulSoup(soup.text, "lxml")
soup.text
lxml_code

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID Live - Coronavirus Statistics - Worldometer</title>
<meta content="Live statistics and coronavirus news tracking the number of confirmed cases, recovered patients, tests, and death toll due to the COVID-19 coronavirus from Wuhan, China. Coronavirus counter with new cases, deaths, and number of tests per 1 Million population. Historical data and info. Daily charts, graphs, news and updates" name="description"/>
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<script src="/js/jquery.min.js"></script>
<script src="/js/bootstrap.min.js"></script>
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/"><span style="color:#FF9900; font-weight:bold">Coronavirus</span></a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<div class="container">
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<div class="row"> <div class="col-md-8">
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: April 29, 2022, 09:22 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">512,301,063 </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,256,838</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>466,157,527</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
 Active Cases
</span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">39,886,698</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">39,845,189</span> (<strong>99.9</strong>%)
<div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">41,509</span> (<strong>0.1</strong>%)
<div style="font-size:13px">Serious or Critical</div><br/>
</div>
</div>
<a class="flip_cases_front" href="javascript: void(0);" style="clear: both;display: block;padding-top:20px;width:100%;">Show Graph</a>
</div>
<div class="panel_back" style="width:100%;height:100%;">
<div id="total-currently-infected-linear"></div>
<script type="text/javascript">
    Highcharts.setOptions({
        lang: {
            thousandsSep: ','
        }
    });

    var y_labels = ['0', '20,000', '40,000', '60,000', '140', '180', '200', '240'];
    Highcharts.chart('total-currently-infected-linear', {


        chart: {
            type: 'line',
            height: (9 / 16 * 100) + '%'
        },

        title: {
            text: null

        },

        /*subtitle: {
            text: '(Number of Infected People)'
        },*/

        xAxis: {

In [ ]:
table_code = lxml_code.table
table_code

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>98,198,105</td>
<td>+1,232</td>
<td>1,459,015</td>
<td>+33</td>
<td>94,092,975</td>
<td>+781</td>
<td>2,646,115</td>
<td>7,139</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>147,768,717</td>
<td>+125,755</td>
<td>1,423,322</td>
<td>+366</td>
<td>125,830,656</td>
<td>+58,443</td>
<td>20,514,739</td>
<td>12,965</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>56,766,069</td>
<td>+125</td>
<td>1,294,061</td>
<td></td>
<td>52,894,740</td>
<td>+549</td>
<td>2,577,268</td>
<td>10,830</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>190,569,564</td>
<td>+19,854</td>
<td>1,816,076</td>
<td>+239</td>
<td>175,623,650</td>
<td>+205,021</td>
<td>13,129,838</td>
<td>9,431</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>7,108,605</td>
<td>+50,021</td>
<td>10,564</td>
<td>+39</td>
<td>6,620,407</td>
<td>+9,445</td>
<td>477,634</td>
<td>173</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>11,889,282</td>
<td></td>
<td>253,785</td>
<td></td>
<td>11,094,393</td>
<td></td>
<td>541,104</td>
<td>971</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>512,301,063</td>
<td>+196,987</td>
<td>6,256,838</td>
<td>+677</td>
<td>466,157,527</td>
<td>+274,239</td>
<td>39,886,698</td>
<td>41,509</td>
<td>65,723</td>
<td>802.7</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<td>
</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">82,954,768</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,020,159 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">80,623,433</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,311,176</td>
<td style="font-weight: bold; text-align:right">1,565</td>
<td style="font-weight: bold; text-align:right">247,972</td>
<td style="font-weight: bold; text-align:right">3,050</td>
<td style="font-weight: bold; text-align:right">1,003,873,530</td>
<td style="font-weight: bold; text-align:right">3,000,821</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,532,930</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<td>4</td><td>328</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,919</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">43,072,486</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">523,753 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">42,530,622</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">18,111</td>
<td style="font-weight: bold; text-align:right">698</td>
<td style="font-weight: bold; text-align:right">30,664</td>
<td style="font-weight: bold; text-align:right">373</td>
<td style="font-weight: bold; text-align:right">836,945,383</td>
<td style="font-weight: bold; text-align:right">595,826</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,404,680,388</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>33</td><td>2,682</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">13</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">30,418,920</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">663,289 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">29,499,422</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">256,209</td>
<td style="font-weight: bold; text-align:right">8,318</td>
<td style="font-weight: bold; text-align:right">141,281</td>
<td style="font-weight: bold; text-align:right">3,081</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,210</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,307,551</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<td>7</td><td>325</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,190</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">28,542,884</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">145,711 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,552,320</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,844,853</td>
<td style="font-weight: bold; text-align:right">1,677</td>
<td style="font-weight: bold; text-align:right">435,528</td>
<td style="font-weight: bold; text-align:right">2,223</td>
<td style="font-weight: bold; text-align:right">266,484,045</td>
<td style="font-weight: bold; text-align:right">4,066,211</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,536,206</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>2</td><td>450</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">28,150</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">24,608,074</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">135,608 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,227,600</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+139,300</td>
<td style="text-align:right;font-weight:bold;">2,244,866</td>
<td style="font-weight: bold; text-align:right">1,446</td>
<td style="font-weight: bold; text-align:right">292,010</td>
<td style="font-weight: bold; text-align:right">1,609</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,451,651</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,271,199</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>621</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">26,639</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">22,025,925</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">174,696 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">21,130,857</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+19</td>
<td style="text-align:right;font-weight:bold;">720,372</td>
<td style="font-weight: bold; text-align:right">310</td>
<td style="font-weight: bold; text-align:right">321,384</td>
<td style="font-weight: bold; text-align:right">2,549</td>
<td style="font-weight: bold; text-align:right">516,977,818</td>
<td style="font-weight: bold; text-align:right">7,543,310</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,534,608</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>3</td><td>392</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">10,511</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">18,174,991</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,710</td>
<td style="font-weight: bold; text-align:right;">375,727 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+161</td>
<td style="font-weight: bold; text-align:right">17,528,963</td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,041</td>
<td style="text-align:right;font-weight:bold;">270,301</td>
<td style="font-weight: bold; text-align:right">2,300</td>
<td style="font-weight: bold; text-align:right">124,445</td>
<td style="font-weight: bold; text-align:right">2,573</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,871,984</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,048,270</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>8</td><td>389</td><td>1</td>
<td style="font-weight: bold; text-align:right">53</td>
<td style="font-weight: bold; text-align:right">1</td>
<td style="font-weight: bold; text-align:right">1,851</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">17,194,616</td>
<td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+50,551</td>
<td style="font-weight: bold; text-align:right;">22,724 </td>
<td style="font-weight: bold;
                                    text-align:right;background-color:red; color:white">+136</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">526</td>
<td style="font-weight: bold; text-align:right">334,855</td>
<td style="font-weight: bold; text-align:right">443</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,775</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,349,433</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>3</td><td>2,260</td><td>3</td>
<td style="font-weight: bold; text-align:right">984</td>
<td style="font-weight: bold; text-align:right">3</td>
<td style="font-weight: bold; text-align:right">315,532</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">16,349,788</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">163,244 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">14,937,738</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,248,806</td>
<td style="font-weight: bold; text-align:right">382</td>
<td style="font-weight: bold; text-align:right">271,140</td>
<td style="font-weight: bold; text-align:right">2,707</td>
<td style="font-weight: bold; text-align:right">213,009,371</td>
<td style="font-weight: bold; text-align:right">3,532,486</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,300,137</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>4</td><td>369</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">20,710</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
<td style="font-weight: bold; text-align:right">15,028,397</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">98,751 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">14,927,975</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,671</td>
<td style="font-weight: bold; text-align:right">975</td>
<td style="font-weight: bold; text-align:right">174,770</td>
<td style="font-weight: bold; text-align:right">1,148</td>
<td style="font-weight: bold; text-align:right">158,778,055</td>
<td style="font-weight: bold; text-align:right">1,846,480</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,989,599</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<td>6</td><td>871</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">19</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
<td style="font-weight: bold; text-align:right">11,833,457</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">104,227 </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">11,347,449</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">381,781</td>
<td style="font-weight: bold; text-align:right">339</td>
<td style="font-weight: bold; text-align:right">252,918</td>
<td style="font-weight: bold; text-align:right">2,228</td>
<td style="font-weight: bold; text-align:right">471,036,328</td>
<td style="font-weight: bold; text-align:right">10,067,522</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,787,714</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<td>4</td><td>449</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>

In [ ]:
tags=table_code.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>98,198,105</td>
 <td>+1,232</td>
 <td>1,459,015</td>
 <td>+33</td>
 <td>94,092,975</td>
 <td>+781</td>
 <td>2,646,115</td>
 <td>7,139</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>147,768,717</td>
 <td>+125,755</td>
 <td>1,423,322</td>
 <td>+366</td>
 <td>125,830,656</td>
 <td>+58,443</td>
 <td>20,514,739</td>
 <td>12,965</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>56,766,069</td>
 <td>+125</td>
 <td>1,294,061</td>
 <td></td>
 <td>52,894,740</td>
 <td>+549</td>
 <td>2,577,268</td>
 <td>10,830</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>190,569,564</td>
 <td>+19,854</td>
 <td>1,816,076</td>
 <td>+239</td>
 <td>175,623,650</td>
 <td>+205,021</td>
 <td>13,129,838</td>
 <td>9,431</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>7,108,605</td>
 <td>+50,021</td>
 <td>10,564</td>
 <td>+39</td>
 <td>6,620,407</td>
 <td>+9,445</td>
 <td>477,634</td>
 <td>173</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>11,889,282</td>
 <td></td>
 <td>253,785</td>
 <td></td>
 <td>11,094,393</td>
 <td></td>
 <td>541,104</td>
 <td>971</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>512,301,063</td>
 <td>+196,987</td>
 <td>6,256,838</td>
 <td>+677</td>
 <td>466,157,527</td>
 <td>+274,239</td>
 <td>39,886,698</td>
 <td>41,509</td>
 <td>65,723</td>
 <td>802.7</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">82,954,768</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,020,159 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">80,623,433</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,311,176</td>
 <td style="font-weight: bold; text-align:right">1,565</td>
 <td style="font-weight: bold; text-align:right">247,972</td>
 <td style="font-weight: bold; text-align:right">3,050</td>
 <td style="font-weight: bold; text-align:right">1,003,873,530</td>
 <td style="font-weight: bold; text-align:right">3,000,821</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,532,930</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>4</td><td>328</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,919</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">43,072,486</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">523,753 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">42,530,622</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">18,111</td>
 <td style="font-weight: bold; text-align:right">698</td>
 <td style="font-weight: bold; text-align:right">30,664</td>
 <td style="font-weight: bold; text-align:right">373</td>
 <td style="font-weight: bold; text-align:right">836,945,383</td>
 <td style="font-weight: bold; text-align:right">595,826</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,404,680,388</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>33</td><td>2,682</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">13</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">30,418,920</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">663,289 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">29,499,422</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">256,209</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">141,281</td>
 <td style="font-weight: bold; text-align:right">3,081</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,210</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,307,551</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>7</td><td>325</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">1,190</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">28,542,884</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">145,711 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">26,552,320</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,844,853</td>
 <td style="font-weight: bold; text-align:right">1,677</td>
 <td style="font-weight: bold; text-align:right">435,528</td>
 <td style="font-weight: bold; text-align:right">2,223</td>
 <td style="font-weight: bold; text-align:right">266,484,045</td>
 <td style="font-weight: bold; text-align:right">4,066,211</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,536,206</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>2</td><td>450</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">28,150</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">24,608,074</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">135,608 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,227,600</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+139,300</td>
 <td style="text-align:right;font-weight:bold;">2,244,866</td>
 <td style="font-weight: bold; text-align:right">1,446</td>
 <td style="font-weight: bold; text-align:right">292,010</td>
 <td style="font-weight: bold; text-align:right">1,609</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,451,651</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">84,271,199</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>3</td><td>621</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">26,639</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">22,025,925</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">174,696 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">21,130,857</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+19</td>
 <td style="text-align:right;font-weight:bold;">720,372</td>
 <td style="font-weight: bold; text-align:right">310</td>
 <td style="font-weight: bold; text-align:right">321,384</td>
 <td style="font-weight: bold; text-align:right">2,549</td>
 <td style="font-weight: bold; text-align:right">516,977,818</td>
 <td style="font-weight: bold; text-align:right">7,543,310</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,534,608</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>3</td><td>392</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">10,511</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">18,174,991</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+7,710</td>
 <td style="font-weight: bold; text-align:right;">375,727 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+161</td>
 <td style="font-weight: bold; text-align:right">17,528,963</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+11,041</td>
 <td style="text-align:right;font-weight:bold;">270,301</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">124,445</td>
 <td style="font-weight: bold; text-align:right">2,573</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,871,984</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">146,048,270</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>8</td><td>389</td><td>1</td>
 <td style="font-weight: bold; text-align:right">53</td>
 <td style="font-weight: bold; text-align:right">1</td>
 <td style="font-weight: bold; text-align:right">1,851</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">17,194,616</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+50,551</td>
 <td style="font-weight: bold; text-align:right;">22,724 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+136</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">526</td>
 <td style="font-weight: bold; text-align:right">334,855</td>
 <td style="font-weight: bold; text-align:right">443</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,775</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,349,433</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>3</td><td>2,260</td><td>3</td>
 <td style="font-weight: bold; text-align:right">984</td>
 <td style="font-weight: bold; text-align:right">3</td>
 <td style="font-weight: bold; text-align:right">315,532</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">16,349,788</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">163,244 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">14,937,738</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,248,806</td>
 <td style="font-weight: bold; text-align:right">382</td>
 <td style="font-weight: bold; text-align:right">271,140</td>
 <td style="font-weight: bold; text-align:right">2,707</td>
 <td style="font-weight: bold; text-align:right">213,009,371</td>
 <td style="font-weight: bold; text-align:right">3,532,486</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,300,137</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>4</td><td>369</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">20,710</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>
 <td style="font-weight: bold; text-align:right">15,028,397</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">98,751 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">14,927,975</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,671</td>
 <td style="font-weight: bold; text-align:right">975</td>
 <td style="font-weight: bold; text-align:right">174,770</td>
 <td style="font-weight: bold; text-align:right">1,148</td>
 <td style="font-weight: bold; text-align:right">158,778,055</td>
 <td style="font-weight: bold; text-align:right">1,846,480</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/turkey-population/">85,989,599</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>6</td><td>871</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">19</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">11,833,457</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">104,227 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">11,347,449</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">381,781</td>
 <td style="font-weight: bold; text-align:right">339</td>
 <td style="font-weight: bold; text-align:right">252,918</td>
 <td style="font-weight: bold; text-align:right">2,228</td>
 <td style="font-weight: bold; text-align:right">471,036,328</td>

In [ ]:
data= []
for tag in tags:
  data.append(tag.text.split('\n')[1:-1])
data

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop'],
 ['',
  '',
  'North America',
  '',
  '98,198,105',
  '+1,232',
  '1,459,015',
  '+33',
  '94,092,975',
  '+781',
  '2,646,115',
  '7,139',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Asia',
  '',
  '147,768,717',
  '+125,755',
  '1,423,322',
  '+366',
  '125,830,656',
  '+58,443',
  '20,514,739',
  '12,965',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'South America',
  '',
  '56,766,069',
  '+125',
  '1,294,061',
  '',
  '52,894,740',
  '+549',
  '2,577,268',
  '10,830',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Europe',
  '',
  '190,569,564',
  '+19,854',
  '1,816,076',
  '+239',
  '175,623,650',
  '+205,021',
  '13,129,838',
  '9,431',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Oceania',
  '',
  '7,108,605',
  '+50,021',
  '10,564',
  '+39',
  '6,620,407',
  '+9,445',
  '477,634',
  '173',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Africa',
  '',
  '11,889,282',
  '',
  '253,785',
  '',
  '11,094,393',
  '',
  '541,104',
  '971',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  '',
  '721',
  '',
  '15',
  '',
  '706',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  'World',
  '512,301,063',
  '+196,987',
  '6,256,838',
  '+677',
  '466,157,527',
  '+274,239',
  '39,886,698',
  '41,509',
  '65,723',
  '802.7',
  '',
  '',
  '',
  'All',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['1',
  'USA',
  '82,954,768',
  '',
  '1,020,159 ',
  '',
  '80,623,433',
  '',
  '1,311,176',
  '1,565',
  '247,972',
  '3,050',
  '1,003,873,530',
  '3,000,821',
  '334,532,930 ',
  'North America',
  '43280',
  '',
  '',
  '3,919'],
 ['2',
  'India',
  '43,072,486',
  '',
  '523,753 ',
  '',
  '42,530,622',
  '',
  '18,111',
  '698',
  '30,664',
  '373',
  '836,945,383',
  '595,826',
  '1,404,680,388 ',
  'Asia',
  '332,6822',
  '',
  '',
  '13'],
 ['3',
  'Brazil',
  '30,418,920',
  '',
  '663,289 ',
  '',
  '29,499,422',
  '',
  '256,209',
  '8,318',
  '141,281',
  '3,081',
  '63,776,166',
  '296,210',
  '215,307,551 ',
  'South America',
  '73253',
  '',
  '',
  '1,190'],
 ['4',
  'France',
  '28,542,884',
  '',
  '145,711 ',
  '',
  '26,552,320',
  '',
  '1,844,853',
  '1,677',
  '435,528',
  '2,223',
  '266,484,045',
  '4,066,211',
  '65,536,206 ',
  'Europe',
  '24500',
  '',
  '',
  '28,150'],
 ['5',
  'Germany',
  '24,608,074',
  '',
  '135,608 ',
  '',
  '22,227,600',
  '+139,300',
  '2,244,866',
  '1,446',
  '292,010',
  '1,609',
  '122,332,384',
  '1,451,651',
  '84,271,199 ',
  'Europe',
  '36211',
  '',
  '',
  '26,639'],
 ['6',
  'UK',
  '22,025,925',
  '',
  '174,696 ',
  '',
  '21,130,857',
  '+19',
  '720,372',
  '310',
  '321,384',
  '2,549',
  '516,977,818',
  '7,543,310',
  '68,534,608 ',
  'Europe',
  '33920',
  '',
  '',
  '10,511'],
 ['7',
  'Russia',
  '18,174,991',
  '+7,710',
  '375,727 ',
  '+161',
  '17,528,963',
  '+11,041',
  '270,301',
  '2,300',
  '124,445',
  '2,573',
  '273,400,000',
  '1,871,984',
  '146,048,270 ',
  'Europe',
  '83891',
  '53',
  '1',
  '1,851'],
 ['8',
  'S. Korea',
  '17,194,616',
  '+50,551',
  '22,724 ',
  '+136',
  'N/A',
  'N/A',
  'N/A',
  '526',
  '334,855',
  '443',
  '15,804,065',
  '307,775',
  '51,349,433 ',
  'Asia',
  '32,2603',
  '984',
  '3',
  '315,532'],
 ['9',
  'Italy',
  '16,349,788',
  '',
  '163,244 ',
  '',
  '14,937,738',
  '',
  '1,248,806',
  '382',
  '271,140',
  '2,707',
  '213,009,371',
  '3,532,486',
  '60,300,137 ',
  'Europe',
  '43690',
  '',
  '',
  '20,710'],
 ['10',
  'Turkey',
  '15,028,397',
  '',
  '98,751 ',
  '',
  '14,927,975',
  '',
  '1,671',
  '975',
  '174,770',
  '1,148',
  '158,778,055',
  '1,846,480',
  '85,989,599 ',
  'Asia',
  '68711',
  '',
  '',
  '19'],
 ['11',
  'Spain',
  '11,833,457',
  '',
  '104,227 ',
  '',
  '11,347,449',
  '',
  '381,781',
  '339',
  '252,918',
  '2,228',
  '471,036,328',
  '10,067,522',
  '46,787,714 ',
  'Europe',
  '44490',
  '',
  '',
  '8,160'],
 ['12',
  'Vietnam',
  '10,638,632',
  '',
  '43,037 ',
  '',
  '9,242,303',
  '',
  '1,353,292',
  '629',
  '107,535',
  '435',
  '85,795,593',
  '867,222',
  '98,931,474 ',
  'Asia',
  '92,2991',
  '',
  '',
  '13,679'],
 ['13',
  'Argentina',
  '9,072,230',
  '',
  '128,542 ',
  '',
  '8,895,999',
  '',
  '47,689',
  '372',
  '197,437',
  '2,797',
  '35,716,069',
  '777,280',
  '45,950,062 ',
  'South America',
  '53571',
  '',
  '',
  '1,038'],
 ['14',
  'Netherlands',
  '8,045,456',
  '',
  '22,239 ',
  '',
  '7,783,785',
  '',
  '239,432',
  '75',
  '467,655',
  '1,293',
  '21,107,399',
  '1,226,901',
  '17,203,828 ',
  'Europe',
  '27741',
  '',
  '',
  '13,917'],
 ['15',
  'Japan',
  '7,813,849',
  '+42,313',
  '29,506 ',
  '+39',
  '7,356,289',
  '+36,932',
  '428,054',
  '173',
  '62,127',
  '235',
  '48,589,480',
  '386,329',
  '125,772,339 ',
  'Asia',
  '164,2633',
  '336',
  '0.3',
  '3,403'],
 ['16',
  'Iran',
  '7,220,402',
  '',
  '141,058 ',
  '',
  '6,977,760',
  '',
  '101,584',
  '1,114',
  '84,009',
  '1,641',
  '50,914,586',
  '592,388',
  '85,948,099 ',
  'Asia',
  '126092',
  '',
  '',
  '1,182'],
 ['17',
  'Colombia',
  '6,092,167',
  '',
  '139,789 ',
  '',
  '5,925,828',
  '',
  '26,550',
  '342',
  '117,452',
  '2,695',
  '34,446,718',
  '664,107',
  '51,869,255 ',
  'South America',
  '93712',
  '',
  '',
  '512'],
 ['18',
  'Indonesia',
  '6,046,072',
  '',
  '156,217 ',
  '',
  '5,881,490',
  '',
  '8,365',
  '2,771',
  '21,687',
  '560',
  '95,397,890',
  '342,193',
  '278,783,952 ',
  'Asia',
  '461,7853',
  '',
  '',
  '30'],
 ['19',
  'Poland',
  '5,995,674',
  '+857',
  '116,042 ',
  '+20',
  '5,334,621',
  '+63',
  '545,011',
  '1,321',
  '158,737',
  '3,072',
  '36,092,285',
  '955,550',
  '37,771,225 ',
  'Europe',
  '63251',
  '23',
  '0.5',
  '14,429'],
 ['20',
  'Australia',
  '5,889,048',
  '+41,696',
  '7,189 ',
  '+26',
  '5,509,057',
  '',
  '372,802',
  '137',
  '226,172',
  '276',
  '69,260,340',
  '2,659,975',
  '26,037,970 ',
  'Australia/Oceania',
  '43,6220',
  '1,601',
  '1.0',
  '14,318'],
 ['21',
  'Mexico',
  '5,737,811',
  '+1,232',
  '324,254 ',
  '+33',
  '5,037,473',
  '+781',
  '376,084',
  '4,798',
  '43,668',
  '2,468',
  '15,794,055',
  '120,202',
  '131,396,426 ',
  'North America',
  '234058',
  '9',
  '0.3',
  '2,862'],
 ['22',
  'Ukraine',
  '5,001,039',
  '',
  '108,380 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '177',
  '115,615',
  '2,506',
  '19,521,252',
  '451,296',
  '43,255,978 ',
  'Europe',
  '93992',
  '',
  '',
  '19,295'],
 ['23',
  'Malaysia',
  '4,443,318',
  '',
  '35,536 ',
  '',
  '4,354,006',
  '',
  '53,776',
  '84',
  '134,158',
  '1,073',
  '58,619,511',
  '1,769,904',
  '33,120,156 ',
  'Asia',
  '79321',
  '',
  '',
  '1,624'],
 ['24',
  'Thailand',
  '4,238,061',
  '+14,053',
  '28,403 ',
  '+129',
  '4,053,751',
  '+16,782',
  '155,907',
  '1,496',
  '60,441',
  '405',
  '17,270,775',
  '246,308',
  '70,118,531 ',
  'Asia',
  '172,4694',
  '200',
  '2',
  '2,223'],
 ['25',
  'Austria',
  '4,135,344',
  '+6,186',
  '18,138 ',
  '+21',
  '4,034,609',
  '+7,765',
  '82,597',
  '99',
  '454,440',
  '1,993',
  '182,842,386',
  '20,092,870',
  '9,099,864 ',
  'Europe',
  '25020',
  '680',
  '2',
  '9,077'],
 ['26',
  'Israel',
  '4,071,491',
  '',
  '10,695 ',
  '',
  '4,033,472',
  '',
  '27,324',
  '220',
  '436,574',
  '1,147',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '28720',
  '',
  '',
  '2,930'],
 ['27',
  'Belgium',
  '4,056,448',
  '',
  '31,439 ',
  '',
  '3,788,380',
  '+19,596',
  '236,629',
  '150',
  '347,258',
  '2,691',
  '33,531,891',
  '2,870,547',
  '11,681,361 ',
  'Europe',
  '33720',
  '',
  '',
  '20,257'],
 ['28',
  'Czechia',
  '3,903,659',
  '+1,561',
  '40,143 ',
  '+8',
  '3,844,988',
  '+1,065',
  '18,528',
  '33',
  '363,296',
  '3,736',
  '55,186,195',
  '5,135,933',
  '10,745,115 ',
  'Europe',
  '32680',
  '145',
  '0.7',
  '1,724'],
 ['29',
  'Portugal',
  '3,791,744',
  '',
  '22,162  ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '61',
  '373,842',
  '2,185',
  '41,165,855',
  '4,058,692',
  '10,142,640 ',
  'Europe',
  '34580',
  '',
  '',
  '88,084'],
 ['30',
  'South Africa',
  '3,780,444',
  '',
  '100,355 ',
  '',
  '3,640,571',
  '',
  '39,518',
  '192',
  '62,313',
  '1,654',
  '24,423,181',
  '402,567',
  '60,668,605 ',
  'Africa',
  '166052',
  '',
  '',
  '651'],
 ['31',
  'Canada',
  '3,741,119',
  '',
  '39,177 ',
  '',
  '3,448,330',
  '',
  '253,612',
  '471',
  '97,567',
  '1,022',
  '60,819,571',
  '1,586,156',
  '38,344,014 ',
  'North America',
  '109791',
  '',
  '',
  '6,614'],
 ['32',
  'Philippines',
  '3,685,222',
  '',
  '60,267 ',
  '',
  '3,615,370',
  '',
  '9,585',
  '289',
  '32,835',
  '537',
  '29,519,689',
  '263,020',
  '112,233,503 ',
  'Asia',
  '301,8624',
  '',
  '',
  '85'],
 ['33',
  'Switzerland',
  '3,602,489',
  '',
  '13,836 ',
  '',
  '3,445,491',
  '+18,701',
  '143,162',
  '87',
  '410,786',
  '1,578',
  '20,767,523',
  '2,368,090',
  '8,769,737 ',
  'Europe',
  '26340',
  '',
  '',
  '16,325'],
 ['34',
  'Peru',
  '3,563,929',
  '',
  '212,798 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '324',
  '105,419',
  '6,294',
  '29,778,939',
  '880,848',
  '33,807,126 ',
  'South America',
  '91591',
  '',
  '',
  '48,228'],
 ['35',
  'Chile',
  '3,553,956',
  '',
  '57,495 ',
  '',
  '3,401,004',
  '',
  '95,457',
  '239',
  '183,055',
  '2,961',
  '36,908,909',
  '1,901,086',
  '19,414,647 ',
  'South America',
  '53381',
  '',
  '',
  '4,917'],
 ['36',
  'Greece',
  '3,309,962',
  '',
  '29,073 ',
  '',
  '3,195,503',
  '',
  '85,386',
  '260',
  '320,408',
  '2,814',
  '79,481,141',
  '7,693,855',
  '10,330,470 ',
  'Europe',
  '33550',
  '',
  '',
  '8,265'],
 ['37',
  'Denmark',
  '2,964,337',
  '',
  '6,135 ',
  '',
  '2,939,098',
  '',
  '19,104',
  '13',
  '508,524',
  '1,052',
  '127,196,800',
  '21,820,249',
  '5,829,301 ',
  'Europe',
  '29500',
  '',
  '',
  '3,277'],
 ['38',
  'Romania',
  '2,891,973',
  '',
  '65,471 ',
  '',
  '2,606,660',
  '',
  '219,842',
  '193',
  '152,174',
  '3,445',
  '22,663,841',
  '1,192,562',
  '19,004,331 ',
  'Europe',
  '72901',
  '',
  '',
  '11,568'],
 ['39',
  'Sweden',
  '2,500,917',
  '',
  '18,739 ',
  '',
  '2,468,078',
  '',
  '14,100',
  '21',
  '244,857',
  '1,835',
  '18,513,445',
  '1,812,591',
  '10,213,801 ',
  'Europe',
  '45451',
  '',
  '',
  '1,380'],
 ['40',
  'Iraq',
  '2,324,847',
  '',
  '25,209 ',
  '',
  '2,297,303',
  '',
  '2,335',
  '20',
  '55,534',
  '602',
  '18,470,495',
  '441,208',
  '41,863,426 ',
  'Asia',
  '181,6612',
  '',
  '',
  '56'],
 ['41',
  'Serbia',
  '2,005,072',
  '',
  '15,980 ',
  '',
  '1,972,747',
  '',
  '16,345',
  '25',
  '231,176',
  '1,842',
  '9,471,803',
  '1,092,056',
  '8,673,369 ',
  'Europe',
  '45431',
  '',
  '',
  '1,885'],
 ['42',
  'Bangladesh',
  '1,952,644',
  '',
  '29,127 ',
  '',
  '1,894,820',
  '',
  '28,697',
  '1,297',
  '11,646',
  '174',
  '13,982,774',
  '83,393',
  '167,673,489 ',
  'Asia',
  '865,75712',
  '',
  '',
  '171'],
 ['43',
  'Hungary',
  '1,901,017',
  '+1,384',
  '46,201 ',
  '+12',
  '1,804,295',
  '+2,482',
  '50,521',
  '41',
  '197,698',
  '4,805',
  '11,339,446',
  '1,179,259',
  '9,615,741 ',
  'Europe',
  '52081',
  '144',
  '1',
  '5,254'],
 ['44',
  'Slovakia',
  '1,780,022',
  '+926',
  '19,891 ',
  '+12',
  '1,742,391',
  '+2,471',
  '17,740',
  '70',
  '325,746',
  '3,640',
  '7,084,258',
  '1,296,426',
  '5,464,452 ',
  'Europe',
  '32751',
  '169',
  '2',
  '3,246'],
 ['45',
  'Jordan',
  '1,694,216',
  '',
  '14,048 ',
  '',
  '1,678,941',
  '',
  '1,227',
  '124',
  '163,104',
  '1,352',
  '16,670,254',
  '1,604,860',
  '10,387,355 ',
  'Asia',
  '67391',
  '',
  '',
  '118'],
 ['46',
  'Georgia',
  '1,654,945',
  '+148',
  '16,807 ',
  '+2',
  '1,636,800',
  '+280',
  '1,338',
  '',
  '416,313',
  '4,228',
  '16,885,842',
  '4,247,753',
  '3,975,241 ',
  'Asia',
  '22370',
  '37',
  '0.5',
  '337'],
 ['47',
  'Pakistan',
  '1,528,347',
  '+75',
  '30,371 ',
  '',
  '1,494,141',
  '',
  '3,835',
  '138',
  '6,683',
  '133',
  '28,137,765',
  '123,038',
  '228,690,978 ',
  'Asia',
  '1507,5308',
  '0.3',
  '',
  '17'],
 ['48',
  'Ireland',
  '1,516,153',
  '',
  '7,076 ',
  '',
  '1,441,736',
  '',
  '67,341',
  '36',
  '300,938',
  '1,404',
  '12,055,978',
  '2,392,962',
  '5,038,099 ',
  'Europe',
  '37120',
  '',
  '',
  '13,366'],
 ['49',
  'Norway',
  '1,425,464',
  '',
  '2,932 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '20',
  '259,253',
  '533',
  '11,002,430',
  '2,001,045',
  '5,498,341 ',
  'Europe',
  '41,8750',
  '',
  '',
  '242,542'],
 ['50',
  'Kazakhstan',
  '1,305,521',
  '+17',
  '13,660 ',
  '',
  '1,291,055',
  '+11',
  '806',
  '24',
  '68,048',
  '712',
  '11,575,012',
  '603,331',
  '19,185,171 ',
  'Asia',
  '151,4042',
  '0.9',
  '',
  '42'],
 ['51',
  'Hong Kong',
  '1,203,481',
  '',
  '9,287 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '115',
  '158,194',
  '1,221',
  '44,972,952',
  '5,911,579',
  '7,607,604 ',
  'Asia',
  '68190',
  '',
  '',
  '155,234'],
 ['52',
  'Singapore',
  '1,193,250',
  '',
  '1,334 ',
  '',
  '1,122,264',
  '',
  '69,652',
  '6',
  '201,086',
  '225',
  '23,712,995',
  '3,996,106',
  '5,934,026 ',
  'Asia',
  '54,4480',
  '',
  '',
  '11,738'],
 ['53',
  'Morocco',
  '1,164,865',
  '',
  '16,069 ',
  '',
  '1,148,406',
  '',
  '390',
  '293',
  '30,893',
  '426',
  '11,237,010',
  '298,015',
  '37,706,217 ',
  'Africa',
  '322,3473',
  '',
  '',
  '10'],
 ['54',
  'Bulgaria',
  '1,155,975',
  '',
  '36,901 ',
  '',
  '974,185',
  '',
  '144,889',
  '86',
  '168,673',
  '5,384',
  '9,834,317',
  '1,434,968',
  '6,853,334 ',
  'Europe',
  '61861',
  '',
  '',
  '21,141'],
 ['55',
  'Croatia',
  '1,120,766',
  '',
  '15,817 ',
  '',
  '1,098,860',
  '',
  '6,089',
  '24',
  '276,103',
  '3,897',
  '4,780,298',
  '1,177,636',
  '4,059,231 ',
  'Europe',
  '42571',
  '',
  '',
  '1,500'],
 ['56',
  'Cuba',
  '1,102,559',
  '',
  '8,525 ',
  '',
  '1,093,026',
  '',
  '1,008',
  '23',
  '97,450',
  '753',
  '12,920,253',
  '1,141,966',
  '11,314,043 ',
  'North America',
  '101,3271',
  '',
  '',
  '89'],
 ['57',
  'Lebanon',
  '1,096,763',
  '',
  '10,382 ',
  '',
  '1,081,031',
  '',
  '5,350',
  '186',
  '162,007',
  '1,534',
  '4,795,578',
  '708,372',
  '6,769,861 ',
  'Asia',
  '66521',
  '',
  '',
  '790'],
 ['58',
  'Lithuania',
  '1,057,675',
  '+527',
  '9,090 ',
  '+3',
  '1,022,618',
  '+1,124',
  '25,967',
  '29',
  '398,636',
  '3,426',
  '8,242,836',
  '3,106,710',
  '2,653,236 ',
  'Europe',
  '32920',
  '199',
  '1',
  '9,787'],
 ['59',
  'Tunisia',
  '1,040,193',
  '',
  '28,550 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '29',
  '86,369',
  '2,371',
  '4,572,976',
  '379,704',
  '12,043,534 ',
  'Africa',
  '124223',
  '',
  '',
  '-1,198.32'],
 ['60',
  'Finland',
  '1,023,013',
  '',
  '3,939 ',
  '',
  '46,000',
  '',
  '973,074',
  '24',
  '184,115',
  '709',
  '10,720,282',
  '1,929,366',
  '5,556,375 ',
  'Europe',
  '51,4111',
  '',
  '',
  '175,127'],
 ['61',
  'Slovenia',
  '1,007,821',
  '',
  '6,588 ',
  '',
  '987,666',
  '',
  '13,567',
  '26',
  '484,656',
  '3,168',
  '2,644,271',
  '1,271,615',
  '2,079,458 ',
  'Europe',
  '23161',
  '',
  '',
  '6,524'],
 ['62',
  'Belarus',
  '979,346',
  '',
  '6,940 ',
  '',
  '928,536',
  '',
  '43,870',
  '',
  '103,704',
  '735',
  '13,135,844',
  '1,390,968',
  '9,443,670 ',
  'Europe',
  '101,3611',
  '',
  '',
  '4,645'],
 ['63',
  'Nepal',
  '978,793',
  '',
  '11,951 ',
  '',
  '966,593',
  '',
  '249',
  '',
  '32,529',
  '397',
  '5,633,459',
  '187,222',
  '30,089,710 ',
  'Asia',
  '312,5185',
  '',
  '',
  '8'],
 ['64',
  'New Zealand',
  '923,847',
  '+8,325',
  '696 ',
  '+13',
  '869,922',
  '+9,438',
  '53,229',
  '',
  '184,692',
  '139',
  '7,075,276',
  '1,414,461',
  '5,002,100 ',
  'Australia/Oceania',
  '57,1871',
  '1,664',
  '3',
  '10,641'],
 ['65',
  'Bolivia',
  '904,883',
  '+125',
  '21,910 ',
  '',
  '858,053',
  '+576',
  '24,920',
  '220',
  '75,643',
  '1,832',
  '2,699,040',
  '225,623',
  '11,962,592 ',
  'South America',
  '135464',
  '10',
  '',
  '2,083'],
 ['66',
  'UAE',
  '898,045',
  '',
  '2,302 ',
  '',
  '881,148',
  '',
  '14,595',
  '',
  '88,847',
  '228',
  '155,438,379',
  '15,378,173',
  '10,107,727 ',
  'Asia',
  '114,3910',
  '',
  '',
  '1,444'],
 ['67',
  'Uruguay',
  '895,775',
  '',
  '7,197 ',
  '',
  '886,654',
  '',
  '1,924',
  '18',
  '256,256',
  '2,059',
  '6,091,188',
  '1,742,517',
  '3,495,626 ',
  'South America',
  '44861',
  '',
  '',
  '550'],
 ['68',
  'Ecuador',
  '869,124',
  '',
  '35,588 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '759',
  '47,938',
  '1,963',
  '2,470,170',
  '136,246',
  '18,130,244 ',
  'South America',
  '215097',
  '',
  '',
  '21,492'],
 ['69',
  'Costa Rica',
  '852,074',
  '',
  '8,405 ',
  '',
  '832,853',
  '',
  '10,816',
  '45',
  '164,534',
  '1,623',
  '4,291,131',
  '828,608',
  '5,178,721 ',
  'North America',
  '66161',
  '',
  '',
  '2,089'],
 ['70',
  'Guatemala',
  '844,989',
  '',
  '17,545 ',
  '',
  '825,142',
  '',
  '2,302',
  '5',
  '45,630',
  '947',
  '4,444,867',
  '240,027',
  '18,518,162 ',
  'North America',
  '221,0554',
  '',
  '',
  '124'],
 ['71',
  'Latvia',
  '822,013',
  '+411',
  '5,760 ',
  '+1',
  '808,909',
  '+952',
  '7,344',
  '11',
  '444,744',
  '3,116',
  '7,174,863',
  '3,881,907',
  '1,848,283 ',
  'Europe',
  '23210',
  '222',
  '0.5',
  '3,973'],
 ['72',
  'Azerbaijan',
  '792,521',
  '',
  '9,707 ',
  '',
  '782,675',
  '',
  '139',
  '',
  '76,904',
  '942',
  '6,801,484',
  '659,993',
  '10,305,392 ',
  'Asia',
  '131,0622',
  '',
  '',
  '13'],
 ['73',
  'Panama',
  '774,549',
  '',
  '8,184 ',
  '',
  '761,123',
  '',
  '5,242',
  '8',
  '174,516',
  '1,844',
  '5,858,021',
  '1,319,885',
  '4,438,281 ',
  'North America',
  '65421',
  '',
  '',
  '1,181'],
 ['74',
  'Saudi Arabia',
  '753,822',
  '',
  '9,085 ',
  '',
  '741,389',
  '',
  '3,348',
  '45',
  '21,057',
  '254',
  '41,872,220',
  '1,169,621',
  '35,799,805 ',
  'Asia',
  '473,9411',
  '',
  '',
  '94'],
 ['75',
  'Sri Lanka',
  '663,301',
  '',
  '16,504 ',
  '',
  '646,118',
  '',
  '679',
  '',
  '30,742',
  '765',
  '6,486,117',
  '300,610',
  '21,576,547 ',
  'Asia',
  '331,3073',
  '',
  '',
  '31'],
 ['76',
  'Paraguay',
  '649,034',
  '',
  '18,795 ',
  '',
  '624,673',
  '',
  '5,566',
  '5',
  '89,008',
  '2,578',
  '2,623,300',
  '359,757',
  '7,291,876 ',
  'South America',
  '113883',
  '',
  '',
  '763'],
 ['77',
  'Kuwait',
  '631,409',
  '',
  '2,555 ',
  '',
  '628,090',
  '',
  '764',
  '8',
  '143,979',
  '583',
  '8,007,805',
  '1,826,005',
  '4,385,424 ',
  'Asia',
  '71,7161',
  '',
  '',
  '174'],
 ['78',
  'Myanmar',
  '612,843',
  '',
  '19,434 ',
  '',
  '591,794',
  '',
  '1,615',
  '',
  '11,128',
  '353',
  '7,935,826',
  '144,096',
  '55,073,214 ',
  'Asia',
  '902,8347',
  '',
  '',
  '29'],
 ['79',
  'Palestine',
  '581,940',
  '',
  '5,353 ',
  '',
  '576,242',
  '',
  '345',
  '17',
  '109,449',
  '1,007',
  '3,078,533',
  '578,998',
  '5,317,005 ',
  'Asia',
  '99932',
  '',
  '',
  '65'],
 ['80',
  'Dominican Republic',
  '579,248',
  '',
  '4,376 ',
  '',
  '574,601',
  '',
  '271',
  '6',
  '52,441',
  '396',
  '3,274,131',
  '296,415',
  '11,045,758 ',

In [ ]:
import csv
f=open('list_data.csv','w')
x=csv.writer(f)
for i in data:
  x.writerow(i)

f.close()

In [ ]:
data[1:8]

[['',
  '',
  'North America',
  '',
  '98,198,105',
  '+1,232',
  '1,459,015',
  '+33',
  '94,092,975',
  '+781',
  '2,646,115',
  '7,139',
  '',
  '',
  '',
  '',
  '',
  'North America',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Asia',
  '',
  '147,768,717',
  '+125,755',
  '1,423,322',
  '+366',
  '125,830,656',
  '+58,443',
  '20,514,739',
  '12,965',
  '',
  '',
  '',
  '',
  '',
  'Asia',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'South America',
  '',
  '56,766,069',
  '+125',
  '1,294,061',
  '',
  '52,894,740',
  '+549',
  '2,577,268',
  '10,830',
  '',
  '',
  '',
  '',
  '',
  'South America',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Europe',
  '',
  '190,569,564',
  '+19,854',
  '1,816,076',
  '+239',
  '175,623,650',
  '+205,021',
  '13,129,838',
  '9,431',
  '',
  '',
  '',
  '',
  '',
  'Europe',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Oceania',
  '',
  '7,108,605',
  '+50,021',
  '10,564',
  '+39',
  '6,620,407',
  '+9,445',
  '477,634',
  '173',
  '',
  '',
  '',
  '',
  '',
  'Australia/Oceania',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  'Africa',
  '',
  '11,889,282',
  '',
  '253,785',
  '',
  '11,094,393',
  '',
  '541,104',
  '971',
  '',
  '',
  '',
  '',
  '',
  'Africa',
  '',
  '',
  '',
  '',
  '',
  '',
  ''],
 ['',
  '',
  '',
  '',
  '721',
  '',
  '15',
  '',
  '706',
  '',
  '0',
  '0',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '']]

In [ ]:
del data[1:9]

In [ ]:
del data[-1:-9:-1]

In [ ]:
data

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop'],
 ['1',
  'USA',
  '82,954,768',
  '',
  '1,020,159 ',
  '',
  '80,623,433',
  '',
  '1,311,176',
  '1,565',
  '247,972',
  '3,050',
  '1,003,873,530',
  '3,000,821',
  '334,532,930 ',
  'North America',
  '43280',
  '',
  '',
  '3,919'],
 ['2',
  'India',
  '43,072,486',
  '',
  '523,753 ',
  '',
  '42,530,622',
  '',
  '18,111',
  '698',
  '30,664',
  '373',
  '836,945,383',
  '595,826',
  '1,404,680,388 ',
  'Asia',
  '332,6822',
  '',
  '',
  '13'],
 ['3',
  'Brazil',
  '30,418,920',
  '',
  '663,289 ',
  '',
  '29,499,422',
  '',
  '256,209',
  '8,318',
  '141,281',
  '3,081',
  '63,776,166',
  '296,210',
  '215,307,551 ',
  'South America',
  '73253',
  '',
  '',
  '1,190'],
 ['4',
  'France',
  '28,542,884',
  '',
  '145,711 ',
  '',
  '26,552,320',
  '',
  '1,844,853',
  '1,677',
  '435,528',
  '2,223',
  '266,484,045',
  '4,066,211',
  '65,536,206 ',
  'Europe',
  '24500',
  '',
  '',
  '28,150'],
 ['5',
  'Germany',
  '24,608,074',
  '',
  '135,608 ',
  '',
  '22,227,600',
  '+139,300',
  '2,244,866',
  '1,446',
  '292,010',
  '1,609',
  '122,332,384',
  '1,451,651',
  '84,271,199 ',
  'Europe',
  '36211',
  '',
  '',
  '26,639'],
 ['6',
  'UK',
  '22,025,925',
  '',
  '174,696 ',
  '',
  '21,130,857',
  '+19',
  '720,372',
  '310',
  '321,384',
  '2,549',
  '516,977,818',
  '7,543,310',
  '68,534,608 ',
  'Europe',
  '33920',
  '',
  '',
  '10,511'],
 ['7',
  'Russia',
  '18,174,991',
  '+7,710',
  '375,727 ',
  '+161',
  '17,528,963',
  '+11,041',
  '270,301',
  '2,300',
  '124,445',
  '2,573',
  '273,400,000',
  '1,871,984',
  '146,048,270 ',
  'Europe',
  '83891',
  '53',
  '1',
  '1,851'],
 ['8',
  'S. Korea',
  '17,194,616',
  '+50,551',
  '22,724 ',
  '+136',
  'N/A',
  'N/A',
  'N/A',
  '526',
  '334,855',
  '443',
  '15,804,065',
  '307,775',
  '51,349,433 ',
  'Asia',
  '32,2603',
  '984',
  '3',
  '315,532'],
 ['9',
  'Italy',
  '16,349,788',
  '',
  '163,244 ',
  '',
  '14,937,738',
  '',
  '1,248,806',
  '382',
  '271,140',
  '2,707',
  '213,009,371',
  '3,532,486',
  '60,300,137 ',
  'Europe',
  '43690',
  '',
  '',
  '20,710'],
 ['10',
  'Turkey',
  '15,028,397',
  '',
  '98,751 ',
  '',
  '14,927,975',
  '',
  '1,671',
  '975',
  '174,770',
  '1,148',
  '158,778,055',
  '1,846,480',
  '85,989,599 ',
  'Asia',
  '68711',
  '',
  '',
  '19'],
 ['11',
  'Spain',
  '11,833,457',
  '',
  '104,227 ',
  '',
  '11,347,449',
  '',
  '381,781',
  '339',
  '252,918',
  '2,228',
  '471,036,328',
  '10,067,522',
  '46,787,714 ',
  'Europe',
  '44490',
  '',
  '',
  '8,160'],
 ['12',
  'Vietnam',
  '10,638,632',
  '',
  '43,037 ',
  '',
  '9,242,303',
  '',
  '1,353,292',
  '629',
  '107,535',
  '435',
  '85,795,593',
  '867,222',
  '98,931,474 ',
  'Asia',
  '92,2991',
  '',
  '',
  '13,679'],
 ['13',
  'Argentina',
  '9,072,230',
  '',
  '128,542 ',
  '',
  '8,895,999',
  '',
  '47,689',
  '372',
  '197,437',
  '2,797',
  '35,716,069',
  '777,280',
  '45,950,062 ',
  'South America',
  '53571',
  '',
  '',
  '1,038'],
 ['14',
  'Netherlands',
  '8,045,456',
  '',
  '22,239 ',
  '',
  '7,783,785',
  '',
  '239,432',
  '75',
  '467,655',
  '1,293',
  '21,107,399',
  '1,226,901',
  '17,203,828 ',
  'Europe',
  '27741',
  '',
  '',
  '13,917'],
 ['15',
  'Japan',
  '7,813,849',
  '+42,313',
  '29,506 ',
  '+39',
  '7,356,289',
  '+36,932',
  '428,054',
  '173',
  '62,127',
  '235',
  '48,589,480',
  '386,329',
  '125,772,339 ',
  'Asia',
  '164,2633',
  '336',
  '0.3',
  '3,403'],
 ['16',
  'Iran',
  '7,220,402',
  '',
  '141,058 ',
  '',
  '6,977,760',
  '',
  '101,584',
  '1,114',
  '84,009',
  '1,641',
  '50,914,586',
  '592,388',
  '85,948,099 ',
  'Asia',
  '126092',
  '',
  '',
  '1,182'],
 ['17',
  'Colombia',
  '6,092,167',
  '',
  '139,789 ',
  '',
  '5,925,828',
  '',
  '26,550',
  '342',
  '117,452',
  '2,695',
  '34,446,718',
  '664,107',
  '51,869,255 ',
  'South America',
  '93712',
  '',
  '',
  '512'],
 ['18',
  'Indonesia',
  '6,046,072',
  '',
  '156,217 ',
  '',
  '5,881,490',
  '',
  '8,365',
  '2,771',
  '21,687',
  '560',
  '95,397,890',
  '342,193',
  '278,783,952 ',
  'Asia',
  '461,7853',
  '',
  '',
  '30'],
 ['19',
  'Poland',
  '5,995,674',
  '+857',
  '116,042 ',
  '+20',
  '5,334,621',
  '+63',
  '545,011',
  '1,321',
  '158,737',
  '3,072',
  '36,092,285',
  '955,550',
  '37,771,225 ',
  'Europe',
  '63251',
  '23',
  '0.5',
  '14,429'],
 ['20',
  'Australia',
  '5,889,048',
  '+41,696',
  '7,189 ',
  '+26',
  '5,509,057',
  '',
  '372,802',
  '137',
  '226,172',
  '276',
  '69,260,340',
  '2,659,975',
  '26,037,970 ',
  'Australia/Oceania',
  '43,6220',
  '1,601',
  '1.0',
  '14,318'],
 ['21',
  'Mexico',
  '5,737,811',
  '+1,232',
  '324,254 ',
  '+33',
  '5,037,473',
  '+781',
  '376,084',
  '4,798',
  '43,668',
  '2,468',
  '15,794,055',
  '120,202',
  '131,396,426 ',
  'North America',
  '234058',
  '9',
  '0.3',
  '2,862'],
 ['22',
  'Ukraine',
  '5,001,039',
  '',
  '108,380 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '177',
  '115,615',
  '2,506',
  '19,521,252',
  '451,296',
  '43,255,978 ',
  'Europe',
  '93992',
  '',
  '',
  '19,295'],
 ['23',
  'Malaysia',
  '4,443,318',
  '',
  '35,536 ',
  '',
  '4,354,006',
  '',
  '53,776',
  '84',
  '134,158',
  '1,073',
  '58,619,511',
  '1,769,904',
  '33,120,156 ',
  'Asia',
  '79321',
  '',
  '',
  '1,624'],
 ['24',
  'Thailand',
  '4,238,061',
  '+14,053',
  '28,403 ',
  '+129',
  '4,053,751',
  '+16,782',
  '155,907',
  '1,496',
  '60,441',
  '405',
  '17,270,775',
  '246,308',
  '70,118,531 ',
  'Asia',
  '172,4694',
  '200',
  '2',
  '2,223'],
 ['25',
  'Austria',
  '4,135,344',
  '+6,186',
  '18,138 ',
  '+21',
  '4,034,609',
  '+7,765',
  '82,597',
  '99',
  '454,440',
  '1,993',
  '182,842,386',
  '20,092,870',
  '9,099,864 ',
  'Europe',
  '25020',
  '680',
  '2',
  '9,077'],
 ['26',
  'Israel',
  '4,071,491',
  '',
  '10,695 ',
  '',
  '4,033,472',
  '',
  '27,324',
  '220',
  '436,574',
  '1,147',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '28720',
  '',
  '',
  '2,930'],
 ['27',
  'Belgium',
  '4,056,448',
  '',
  '31,439 ',
  '',
  '3,788,380',
  '+19,596',
  '236,629',
  '150',
  '347,258',
  '2,691',
  '33,531,891',
  '2,870,547',
  '11,681,361 ',
  'Europe',
  '33720',
  '',
  '',
  '20,257'],
 ['28',
  'Czechia',
  '3,903,659',
  '+1,561',
  '40,143 ',
  '+8',
  '3,844,988',
  '+1,065',
  '18,528',
  '33',
  '363,296',
  '3,736',
  '55,186,195',
  '5,135,933',
  '10,745,115 ',
  'Europe',
  '32680',
  '145',
  '0.7',
  '1,724'],
 ['29',
  'Portugal',
  '3,791,744',
  '',
  '22,162  ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '61',
  '373,842',
  '2,185',
  '41,165,855',
  '4,058,692',
  '10,142,640 ',
  'Europe',
  '34580',
  '',
  '',
  '88,084'],
 ['30',
  'South Africa',
  '3,780,444',
  '',
  '100,355 ',
  '',
  '3,640,571',
  '',
  '39,518',
  '192',
  '62,313',
  '1,654',
  '24,423,181',
  '402,567',
  '60,668,605 ',
  'Africa',
  '166052',
  '',
  '',
  '651'],
 ['31',
  'Canada',
  '3,741,119',
  '',
  '39,177 ',
  '',
  '3,448,330',
  '',
  '253,612',
  '471',
  '97,567',
  '1,022',
  '60,819,571',
  '1,586,156',
  '38,344,014 ',
  'North America',
  '109791',
  '',
  '',
  '6,614'],
 ['32',
  'Philippines',
  '3,685,222',
  '',
  '60,267 ',
  '',
  '3,615,370',
  '',
  '9,585',
  '289',
  '32,835',
  '537',
  '29,519,689',
  '263,020',
  '112,233,503 ',
  'Asia',
  '301,8624',
  '',
  '',
  '85'],
 ['33',
  'Switzerland',
  '3,602,489',
  '',
  '13,836 ',
  '',
  '3,445,491',
  '+18,701',
  '143,162',
  '87',
  '410,786',
  '1,578',
  '20,767,523',
  '2,368,090',
  '8,769,737 ',
  'Europe',
  '26340',
  '',
  '',
  '16,325'],
 ['34',
  'Peru',
  '3,563,929',
  '',
  '212,798 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '324',
  '105,419',
  '6,294',
  '29,778,939',
  '880,848',
  '33,807,126 ',
  'South America',
  '91591',
  '',
  '',
  '48,228'],
 ['35',
  'Chile',
  '3,553,956',
  '',
  '57,495 ',
  '',
  '3,401,004',
  '',
  '95,457',
  '239',
  '183,055',
  '2,961',
  '36,908,909',
  '1,901,086',
  '19,414,647 ',
  'South America',
  '53381',
  '',
  '',
  '4,917'],
 ['36',
  'Greece',
  '3,309,962',
  '',
  '29,073 ',
  '',
  '3,195,503',
  '',
  '85,386',
  '260',
  '320,408',
  '2,814',
  '79,481,141',
  '7,693,855',
  '10,330,470 ',
  'Europe',
  '33550',
  '',
  '',
  '8,265'],
 ['37',
  'Denmark',
  '2,964,337',
  '',
  '6,135 ',
  '',
  '2,939,098',
  '',
  '19,104',
  '13',
  '508,524',
  '1,052',
  '127,196,800',
  '21,820,249',
  '5,829,301 ',
  'Europe',
  '29500',
  '',
  '',
  '3,277'],
 ['38',
  'Romania',
  '2,891,973',
  '',
  '65,471 ',
  '',
  '2,606,660',
  '',
  '219,842',
  '193',
  '152,174',
  '3,445',
  '22,663,841',
  '1,192,562',
  '19,004,331 ',
  'Europe',
  '72901',
  '',
  '',
  '11,568'],
 ['39',
  'Sweden',
  '2,500,917',
  '',
  '18,739 ',
  '',
  '2,468,078',
  '',
  '14,100',
  '21',
  '244,857',
  '1,835',
  '18,513,445',
  '1,812,591',
  '10,213,801 ',
  'Europe',
  '45451',
  '',
  '',
  '1,380'],
 ['40',
  'Iraq',
  '2,324,847',
  '',
  '25,209 ',
  '',
  '2,297,303',
  '',
  '2,335',
  '20',
  '55,534',
  '602',
  '18,470,495',
  '441,208',
  '41,863,426 ',
  'Asia',
  '181,6612',
  '',
  '',
  '56'],
 ['41',
  'Serbia',
  '2,005,072',
  '',
  '15,980 ',
  '',
  '1,972,747',
  '',
  '16,345',
  '25',
  '231,176',
  '1,842',
  '9,471,803',
  '1,092,056',
  '8,673,369 ',
  'Europe',
  '45431',
  '',
  '',
  '1,885'],
 ['42',
  'Bangladesh',
  '1,952,644',
  '',
  '29,127 ',
  '',
  '1,894,820',
  '',
  '28,697',
  '1,297',
  '11,646',
  '174',
  '13,982,774',
  '83,393',
  '167,673,489 ',
  'Asia',
  '865,75712',
  '',
  '',
  '171'],
 ['43',
  'Hungary',
  '1,901,017',
  '+1,384',
  '46,201 ',
  '+12',
  '1,804,295',
  '+2,482',
  '50,521',
  '41',
  '197,698',
  '4,805',
  '11,339,446',
  '1,179,259',
  '9,615,741 ',
  'Europe',
  '52081',
  '144',
  '1',
  '5,254'],
 ['44',
  'Slovakia',
  '1,780,022',
  '+926',
  '19,891 ',
  '+12',
  '1,742,391',
  '+2,471',
  '17,740',
  '70',
  '325,746',
  '3,640',
  '7,084,258',
  '1,296,426',
  '5,464,452 ',
  'Europe',
  '32751',
  '169',
  '2',
  '3,246'],
 ['45',
  'Jordan',
  '1,694,216',
  '',
  '14,048 ',
  '',
  '1,678,941',
  '',
  '1,227',
  '124',
  '163,104',
  '1,352',
  '16,670,254',
  '1,604,860',
  '10,387,355 ',
  'Asia',
  '67391',
  '',
  '',
  '118'],
 ['46',
  'Georgia',
  '1,654,945',
  '+148',
  '16,807 ',
  '+2',
  '1,636,800',
  '+280',
  '1,338',
  '',
  '416,313',
  '4,228',
  '16,885,842',
  '4,247,753',
  '3,975,241 ',
  'Asia',
  '22370',
  '37',
  '0.5',
  '337'],
 ['47',
  'Pakistan',
  '1,528,347',
  '+75',
  '30,371 ',
  '',
  '1,494,141',
  '',
  '3,835',
  '138',
  '6,683',
  '133',
  '28,137,765',
  '123,038',
  '228,690,978 ',
  'Asia',
  '1507,5308',
  '0.3',
  '',
  '17'],
 ['48',
  'Ireland',
  '1,516,153',
  '',
  '7,076 ',
  '',
  '1,441,736',
  '',
  '67,341',
  '36',
  '300,938',
  '1,404',
  '12,055,978',
  '2,392,962',
  '5,038,099 ',
  'Europe',
  '37120',
  '',
  '',
  '13,366'],
 ['49',
  'Norway',
  '1,425,464',
  '',
  '2,932 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '20',
  '259,253',
  '533',
  '11,002,430',
  '2,001,045',
  '5,498,341 ',
  'Europe',
  '41,8750',
  '',
  '',
  '242,542'],
 ['50',
  'Kazakhstan',
  '1,305,521',
  '+17',
  '13,660 ',
  '',
  '1,291,055',
  '+11',
  '806',
  '24',
  '68,048',
  '712',
  '11,575,012',
  '603,331',
  '19,185,171 ',
  'Asia',
  '151,4042',
  '0.9',
  '',
  '42'],
 ['51',
  'Hong Kong',
  '1,203,481',
  '',
  '9,287 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '115',
  '158,194',
  '1,221',
  '44,972,952',
  '5,911,579',
  '7,607,604 ',
  'Asia',
  '68190',
  '',
  '',
  '155,234'],
 ['52',
  'Singapore',
  '1,193,250',
  '',
  '1,334 ',
  '',
  '1,122,264',
  '',
  '69,652',
  '6',
  '201,086',
  '225',
  '23,712,995',
  '3,996,106',
  '5,934,026 ',
  'Asia',
  '54,4480',
  '',
  '',
  '11,738'],
 ['53',
  'Morocco',
  '1,164,865',
  '',
  '16,069 ',
  '',
  '1,148,406',
  '',
  '390',
  '293',
  '30,893',
  '426',
  '11,237,010',
  '298,015',
  '37,706,217 ',
  'Africa',
  '322,3473',
  '',
  '',
  '10'],
 ['54',
  'Bulgaria',
  '1,155,975',
  '',
  '36,901 ',
  '',
  '974,185',
  '',
  '144,889',
  '86',
  '168,673',
  '5,384',
  '9,834,317',
  '1,434,968',
  '6,853,334 ',
  'Europe',
  '61861',
  '',
  '',
  '21,141'],
 ['55',
  'Croatia',
  '1,120,766',
  '',
  '15,817 ',
  '',
  '1,098,860',
  '',
  '6,089',
  '24',
  '276,103',
  '3,897',
  '4,780,298',
  '1,177,636',
  '4,059,231 ',
  'Europe',
  '42571',
  '',
  '',
  '1,500'],
 ['56',
  'Cuba',
  '1,102,559',
  '',
  '8,525 ',
  '',
  '1,093,026',
  '',
  '1,008',
  '23',
  '97,450',
  '753',
  '12,920,253',
  '1,141,966',
  '11,314,043 ',
  'North America',
  '101,3271',
  '',
  '',
  '89'],
 ['57',
  'Lebanon',
  '1,096,763',
  '',
  '10,382 ',
  '',
  '1,081,031',
  '',
  '5,350',
  '186',
  '162,007',
  '1,534',
  '4,795,578',
  '708,372',
  '6,769,861 ',
  'Asia',
  '66521',
  '',
  '',
  '790'],
 ['58',
  'Lithuania',
  '1,057,675',
  '+527',
  '9,090 ',
  '+3',
  '1,022,618',
  '+1,124',
  '25,967',
  '29',
  '398,636',
  '3,426',
  '8,242,836',
  '3,106,710',
  '2,653,236 ',
  'Europe',
  '32920',
  '199',
  '1',
  '9,787'],
 ['59',
  'Tunisia',
  '1,040,193',
  '',
  '28,550 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '29',
  '86,369',
  '2,371',
  '4,572,976',
  '379,704',
  '12,043,534 ',
  'Africa',
  '124223',
  '',
  '',
  '-1,198.32'],
 ['60',
  'Finland',
  '1,023,013',
  '',
  '3,939 ',
  '',
  '46,000',
  '',
  '973,074',
  '24',
  '184,115',
  '709',
  '10,720,282',
  '1,929,366',
  '5,556,375 ',
  'Europe',
  '51,4111',
  '',
  '',
  '175,127'],
 ['61',
  'Slovenia',
  '1,007,821',
  '',
  '6,588 ',
  '',
  '987,666',
  '',
  '13,567',
  '26',
  '484,656',
  '3,168',
  '2,644,271',
  '1,271,615',
  '2,079,458 ',
  'Europe',
  '23161',
  '',
  '',
  '6,524'],
 ['62',
  'Belarus',
  '979,346',
  '',
  '6,940 ',
  '',
  '928,536',
  '',
  '43,870',
  '',
  '103,704',
  '735',
  '13,135,844',
  '1,390,968',
  '9,443,670 ',
  'Europe',
  '101,3611',
  '',
  '',
  '4,645'],
 ['63',
  'Nepal',
  '978,793',
  '',
  '11,951 ',
  '',
  '966,593',
  '',
  '249',
  '',
  '32,529',
  '397',
  '5,633,459',
  '187,222',
  '30,089,710 ',
  'Asia',
  '312,5185',
  '',
  '',
  '8'],
 ['64',
  'New Zealand',
  '923,847',
  '+8,325',
  '696 ',
  '+13',
  '869,922',
  '+9,438',
  '53,229',
  '',
  '184,692',
  '139',
  '7,075,276',
  '1,414,461',
  '5,002,100 ',
  'Australia/Oceania',
  '57,1871',
  '1,664',
  '3',
  '10,641'],
 ['65',
  'Bolivia',
  '904,883',
  '+125',
  '21,910 ',
  '',
  '858,053',
  '+576',
  '24,920',
  '220',
  '75,643',
  '1,832',
  '2,699,040',
  '225,623',
  '11,962,592 ',
  'South America',
  '135464',
  '10',
  '',
  '2,083'],
 ['66',
  'UAE',
  '898,045',
  '',
  '2,302 ',
  '',
  '881,148',
  '',
  '14,595',
  '',
  '88,847',
  '228',
  '155,438,379',
  '15,378,173',
  '10,107,727 ',
  'Asia',
  '114,3910',
  '',
  '',
  '1,444'],
 ['67',
  'Uruguay',
  '895,775',
  '',
  '7,197 ',
  '',
  '886,654',
  '',
  '1,924',
  '18',
  '256,256',
  '2,059',
  '6,091,188',
  '1,742,517',
  '3,495,626 ',
  'South America',
  '44861',
  '',
  '',
  '550'],
 ['68',
  'Ecuador',
  '869,124',
  '',
  '35,588 ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '759',
  '47,938',
  '1,963',
  '2,470,170',
  '136,246',
  '18,130,244 ',
  'South America',
  '215097',
  '',
  '',
  '21,492'],
 ['69',
  'Costa Rica',
  '852,074',
  '',
  '8,405 ',
  '',
  '832,853',
  '',
  '10,816',
  '45',
  '164,534',
  '1,623',
  '4,291,131',
  '828,608',
  '5,178,721 ',
  'North America',
  '66161',
  '',
  '',
  '2,089'],
 ['70',
  'Guatemala',
  '844,989',
  '',
  '17,545 ',
  '',
  '825,142',
  '',
  '2,302',
  '5',
  '45,630',
  '947',
  '4,444,867',
  '240,027',
  '18,518,162 ',
  'North America',
  '221,0554',
  '',
  '',
  '124'],
 ['71',
  'Latvia',
  '822,013',
  '+411',
  '5,760 ',
  '+1',
  '808,909',
  '+952',
  '7,344',
  '11',
  '444,744',
  '3,116',
  '7,174,863',
  '3,881,907',
  '1,848,283 ',
  'Europe',
  '23210',
  '222',
  '0.5',
  '3,973'],
 ['72',
  'Azerbaijan',
  '792,521',
  '',
  '9,707 ',
  '',
  '782,675',
  '',
  '139',
  '',
  '76,904',
  '942',
  '6,801,484',
  '659,993',
  '10,305,392 ',
  'Asia',
  '131,0622',
  '',
  '',
  '13'],
 ['73',
  'Panama',
  '774,549',
  '',
  '8,184 ',
  '',
  '761,123',
  '',
  '5,242',
  '8',
  '174,516',
  '1,844',
  '5,858,021',
  '1,319,885',
  '4,438,281 ',
  'North America',
  '65421',
  '',
  '',
  '1,181'],
 ['74',
  'Saudi Arabia',
  '753,822',
  '',
  '9,085 ',
  '',
  '741,389',
  '',
  '3,348',
  '45',
  '21,057',
  '254',
  '41,872,220',
  '1,169,621',
  '35,799,805 ',
  'Asia',
  '473,9411',
  '',
  '',
  '94'],
 ['75',
  'Sri Lanka',
  '663,301',
  '',
  '16,504 ',
  '',
  '646,118',
  '',
  '679',
  '',
  '30,742',
  '765',
  '6,486,117',
  '300,610',
  '21,576,547 ',
  'Asia',
  '331,3073',
  '',
  '',
  '31'],
 ['76',
  'Paraguay',
  '649,034',
  '',
  '18,795 ',
  '',
  '624,673',
  '',
  '5,566',
  '5',
  '89,008',
  '2,578',
  '2,623,300',
  '359,757',
  '7,291,876 ',
  'South America',
  '113883',
  '',
  '',
  '763'],
 ['77',
  'Kuwait',
  '631,409',
  '',
  '2,555 ',
  '',
  '628,090',
  '',
  '764',
  '8',
  '143,979',
  '583',
  '8,007,805',
  '1,826,005',
  '4,385,424 ',
  'Asia',
  '71,7161',
  '',
  '',
  '174'],
 ['78',
  'Myanmar',
  '612,843',
  '',
  '19,434 ',
  '',
  '591,794',
  '',
  '1,615',
  '',
  '11,128',
  '353',
  '7,935,826',
  '144,096',
  '55,073,214 ',
  'Asia',
  '902,8347',
  '',
  '',
  '29'],
 ['79',
  'Palestine',
  '581,940',
  '',
  '5,353 ',
  '',
  '576,242',
  '',
  '345',
  '17',
  '109,449',
  '1,007',
  '3,078,533',
  '578,998',
  '5,317,005 ',
  'Asia',
  '99932',
  '',
  '',
  '65'],
 ['80',
  'Dominican Republic',
  '579,248',
  '',
  '4,376 ',
  '',
  '574,601',
  '',
  '271',
  '6',
  '52,441',
  '396',
  '3,274,131',
  '296,415',
  '11,045,758 ',
  'North America',
  '192,5243',
  '',
  '',
  '25'],
 ['81',
  'Estonia',
  '571,917',
  '+292',
  '2,538 ',
  '+1',
  '510,350',
  '+608',
  '59,029',
  '3',
  '430,609',
  '1,911',
  '3,324,537',
  '2,503,120',
  '1,328,157 ',
  'Europe',
  '25230',
  '220',
  '0.8',
  '44,444'],
 ['82',
  'Bahrain',
  '567,988',
  '',
  '1,475 ',
  '',
  '562,988',
  '',
  '3,525',
  '4',
  '313,969',
  '815',
  '9,715,743',
  '5,370,609',
  '1,809,058 ',
  'Asia',
  '31,2260',
  '',
  '',
  '1,949'],
 ['83',
  'Venezuela',
  '522,271',
  '',
  '5,707 ',
  '',
  '515,653',
  '',
  '911',
  '230',
  '18,462',
  '202',
  '3,359,014',
  '118,737',
  '28,289,416 ',
  'South America',
  '544,9578',
  '',
  '',
  '32'],
 ['84',
  'Moldova',
  '516,986',
  '',
  '11,489 ',
  '',
  '504,142',
  '',
  '1,355',
  '49',
  '128,702',
  '2,860',
  '3,216,305',
  '800,691',
  '4,016,912 ',
  'Europe',
  '83501',
  '',
  '',
  '337'],
 ['85',
  'Egypt',
  '515,645',
  '',
  '24,613 ',
  '',
  '442,182',
  '',
  '48,850',
  '122',
  '4,872',
  '233',
  '3,693,367',
  '34,894',
  '105,843,882 ',
  'Africa',
  '2054,30029',
  '',
  '',
  '462'],
 ['86',
  'Libya',
  '501,904',
  '',
  '6,430 ',
  '',
  '490,973',
  '',
  '4,501',
  '101',
  '71,281',
  '913',
  '2,477,219',
  '351,817',
  '7,041,215 ',
  'Africa',
  '141,0953',
  '',
  '',
  '639'],
 ['87',
  'Ethiopia',
  '470,515',
  '',
  '7,510 ',
  '',
  '455,292',
  '',
  '7,713',
  '13',
  '3,916',
  '63',
  '4,781,317',
  '39,798',
  '120,140,247 ',
  'Africa',
  '25515,99725',
  '',
  '',
  '64'],
 ['88',
  'Cyprus',
  '470,481',
  '',
  '1,011 ',
  '',
  '124,370',
  '',
  '345,100',
  '60',
  '384,586',
  '826',
  '9,477,138',
  '7,746,905',
  '1,223,345 ',
  'Asia',
  '31,2100',

In [ ]:
import csv
f=open('list_data.csv','w')
x=csv.writer(f)
for i in data:
  x.writerow(i)

f.close()

In [ ]:
import pandas as pd
df = pd.read_csv('list_data.csv')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"82,954,768",NaN,"1,020,159",NaN,"80,623,433",NaN,"1,311,176","1,565",...,"1,003,873,530","3,000,821","334,532,930",North America,43280,NaN,NaN,"3,919",NaN,NaN
1,2,India,"43,072,486",NaN,"523,753",NaN,"42,530,622",NaN,"18,111",698,...,"836,945,383","595,826","1,404,680,388",Asia,"332,6822",NaN,NaN,13,NaN,NaN
2,3,Brazil,"30,418,920",NaN,"663,289",NaN,"29,499,422",NaN,"256,209","8,318",...,"63,776,166","296,210","215,307,551",South America,73253,NaN,NaN,"1,190",NaN,NaN
3,4,France,"28,542,884",NaN,"145,711",NaN,"26,552,320",NaN,"1,844,853","1,677",...,"266,484,045","4,066,211","65,536,206",Europe,24500,NaN,NaN,"28,150",NaN,NaN
4,5,Germany,"24,608,074",NaN,"135,608",NaN,"22,227,600","+139,300","2,244,866","1,446",...,"122,332,384","1,451,651","84,271,199",Europe,36211,NaN,NaN,"26,639",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,224,Niue,8,NaN,,NaN,7,NaN,1,NaN,...,NaN,NaN,"1,646",Australia/Oceania,206,NaN,NaN,608,NaN,NaN
224,225,Nauru,4,NaN,,NaN,3,NaN,1,NaN,...,NaN,NaN,"10,948",Australia/Oceania,"2,737",NaN,NaN,91,NaN,NaN
225,226,Micronesia,3,NaN,,NaN,1,NaN,2,NaN,...,NaN,NaN,"117,216",Australia/Oceania,"39,072",NaN,NaN,17,NaN,NaN
226,227,Saint Helena,2,NaN,,NaN,2,NaN,0,NaN,...,NaN,NaN,"6,110",Africa,"3,055",NaN,NaN,NaN,NaN,NaN
227,228,China,"214,243","+5,659","4,975",52.0,"180,951","+2,796","28,317",417,...,"160,000,000","111,163","1,439,323,776",Asia,"6,718289,3119",4,0.04,20,NaN,NaN

In [ ]:
new_data=df.iloc[0:10]
# country=df['Country,other']
new_data

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,TotalTests,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
0,1,USA,"82,954,768",NaN,"1,020,159",NaN,"80,623,433",NaN,"1,311,176","1,565",...,"1,003,873,530","3,000,821","334,532,930",North America,43280,NaN,NaN,"3,919",NaN,NaN
1,2,India,"43,072,486",NaN,"523,753",NaN,"42,530,622",NaN,"18,111",698,...,"836,945,383","595,826","1,404,680,388",Asia,"332,6822",NaN,NaN,13,NaN,NaN
2,3,Brazil,"30,418,920",NaN,"663,289",NaN,"29,499,422",NaN,"256,209","8,318",...,"63,776,166","296,210","215,307,551",South America,73253,NaN,NaN,"1,190",NaN,NaN
3,4,France,"28,542,884",NaN,"145,711",NaN,"26,552,320",NaN,"1,844,853","1,677",...,"266,484,045","4,066,211","65,536,206",Europe,24500,NaN,NaN,"28,150",NaN,NaN
4,5,Germany,"24,608,074",NaN,"135,608",NaN,"22,227,600","+139,300","2,244,866","1,446",...,"122,332,384","1,451,651","84,271,199",Europe,36211,NaN,NaN,"26,639",NaN,NaN
5,6,UK,"22,025,925",NaN,"174,696",NaN,"21,130,857",+19,"720,372",310,...,"516,977,818","7,543,310","68,534,608",Europe,33920,NaN,NaN,"10,511",NaN,NaN
6,7,Russia,"18,174,991","+7,710","375,727",161.0,"17,528,963","+11,041","270,301","2,300",...,"273,400,000","1,871,984","146,048,270",Europe,83891,53,1.0,"1,851",NaN,NaN
7,8,S. Korea,"17,194,616","+50,551","22,724",136.0,NaN,NaN,NaN,526,...,"15,804,065","307,775","51,349,433",Asia,"32,2603",984,3.0,"315,532",NaN,NaN
8,9,Italy,"16,349,788",NaN,"163,244",NaN,"14,937,738",NaN,"1,248,806",382,...,"213,009,371","3,532,486","60,300,137",Europe,43690,NaN,NaN,"20,710",NaN,NaN
9,10,Turkey,"15,028,397",NaN,"98,751",NaN,"14,927,975",NaN,"1,671",975,...,"158,778,055","1,846,480","85,989,599",Asia,68711,NaN,NaN,19,NaN,NaN

In [ ]:
country=list(new_data['Country,Other'])
country

['USA',
 'India',
 'Brazil',
 'France',
 'Germany',
 'UK',
 'Russia',
 'S. Korea',
 'Italy',
 'Turkey']

In [ ]:
country=list(new_data['Country,Other'])
country
cases=list(new_data['TotalCases'])


cleaned_cases=[]
for case in cases:
  x=case.replace(',','')
  cleaned_cases.append(int(x))

cleaned_cases

[82954768,
 43072486,
 30418920,
 28542884,
 24608074,
 22025925,
 18174991,
 17194616,
 16349788,
 15028397]

In [ ]:
import plotly.graph_objects as go
fig = go.Figure([go.Bar(x=country,y=cleaned_cases)])
fig.show()